frontend/frontend/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'frontend.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^', include('mod.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

frontend/mod/urls.py
from django.conf.urls import patterns, url

from mod import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^success/$', views.success, name='success'),
	url(r'^list/$', views.list, name='list'),
)

frontend/mod/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

from django.core.exceptions import ValidationError

def validate_number(value):
	if (not str(value).startswith('502') or not len(str(value))==11):
		raise ValidationError('%s is not a valid number' % value)

# Create your models here.

class Message(models.Model):
	text = models.CharField(max_length=160)
	created_at = models.DateTimeField(auto_now_add=True)
	sent_at = models.DateTimeField(null=True)
	receivers = models.IntegerField(default=0)
	status = models.CharField(max_length=32)

class Receiver(models.Model):
	number = models.BigIntegerField(validators=[validate_number])
	message = models.ForeignKey('Message')
	enqueued = models.BooleanField(default=False, db_index=True)

class MessageForm(ModelForm):
	class Meta:
		model=Message
		fields = ['text']
	file_field = forms.FileField()

frontend/mod/views.py
import csv
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render,redirect
from django.core.exceptions import ValidationError
from mod import models
#from django.http import HttpResponse
from django.db import transaction
import os
#from django.template import loader

# Create your views here.

def index(request):
	if (request.method=="POST"):
		form = models.MessageForm(request.POST, request.FILES)
		if form.is_valid():
			numbers = request.FILES['file_field']
			path = settings.MEDIA_ROOT + "/tmp.csv"
			handle_file(numbers, path)
			with transaction.atomic():
				message = form.save()
				count = 0
				with open(path, 'rt') as numbers:
					reader = csv.reader(numbers)
					for row in reader:
						count = count+1
						n = models.Receiver(number=row[0], message=message)
						try:
							n.clean_fields()
						except ValidationError:
							messages.error(request, 'El formato de uno o más números en el csv no es correcto. Abortando.')
							return render(request, 'mod/index.html', {'form' : form})
						n.save()
					message.receivers = count
					message.save()
					os.popen('java -jar enqueuer.jar ' + str(message.id));
			return redirect('success')
	else:
		form = models.MessageForm()
	return render(request, 'mod/index.html', {'form' : form})


def success(request):
	return render(request, 'mod/success.html')

def list(request):
	messages = models.Message.objects.all()
	return render(request, 'mod/list.html', {'rows' : messages})

def handle_file(f, path):
	with open(path, 'wb+') as destination:
		for chunk in f.chunks():
			destination.write(chunk)

frontend/mod/templates/mod/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}Envío de mensajes{% endblock %}</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		{% bootstrap_css %}
		{% bootstrap_javascript %}

	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">Simulador</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		      	{% block menu_items %}
		        <li><a href="/">Nuevo mensaje</a></li>
		        <li><a href="/list">Lista de mensajes</a></li>
		        {% endblock %}
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
		{% bootstrap_messages %}
		<div class="well">{%block content %}{% endblock%}</div>
	</body>
</html>

frontend/mod/templates/mod/index.html
{% extends 'mod/base.html' %}
{% load bootstrap3 %}


{% block content %}
<h1>Nuevo mensaje</h1>
<form action="." class="form" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form%}
	{% buttons %}
		<button class="btn btn-primary" type="submit">Enviar</input>
	{% endbuttons %}
</form>
<script type="text/javascript">

	var acentos = "ÃÀÁÄÂÈÉËÊÌÍÏÎÒÓÖÔÙÚÜÛãàáäâèéëêìíïîòóöôùúüûÑñÇç";

	$('#id_text').keypress(function(event){
		if (acentos.indexOf(String.fromCharCode(event.charCode))> -1){
			event.preventDefault();
		}
	});
</script>
{% endblock %}

frontend/mod/templates/mod/list.html
{% extends 'mod/base.html' %}
{% load bootstrap3 %}


{% block content %}
<h1>Listado de mensajes</h1>

<table class="table">
	<tr>
		<th>Id</th>
		<th>Texto</th>
		<th>Status</th>
		<th>Receptores</th>
	</tr>
	{% for row in rows %}
		<tr>
			<td>{{row.id}}</td>
			<td>{{row.text}}</td>
			<td>{{row.status}}</td>
			<td>{{row.receivers}}</td>
		</tr>
	{% endfor %}	
</table>


{% endblock %}

frontend/mod/templates/mod/success.html
{% extends 'mod/base.html' %}
{% load bootstrap3 %}


{% block content %}
<h1>Mensaje enviado</h1>
<p>El mensaje ha sido enviado a la cola de procesos</p>
{% endblock %}